/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootstrapAssets;
extern const Sifteo::AssetImage EnzConcSelected;
extern const Sifteo::AssetImage Background;
extern const Sifteo::AssetImage RMS;
extern const Sifteo::AssetImage RctOverview;
extern const Sifteo::AssetImage Simulate;
extern const Sifteo::AssetImage Molecule;
extern const Sifteo::AssetImage Enzyme;
extern const Sifteo::AssetImage MolOverview;
extern const Sifteo::AssetImage MolEquation;
extern const Sifteo::AssetImage RctRate;
extern const Sifteo::AssetImage MolGraph;
extern const Sifteo::AssetImage MolConc;
extern const Sifteo::AssetImage MolConcSelected;
extern const Sifteo::AssetImage EnzConc;
extern const Sifteo::AssetImage RctRateSelected;
extern const Sifteo::AssetImage Play;
extern const Sifteo::AssetImage Pause;
extern const Sifteo::AssetImage Stop;
extern const Sifteo::AssetImage Quit;
extern const Sifteo::AssetImage Direction;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::PinnedAssetImage SmallFont;
extern const Sifteo::AssetImage Model;
extern const Sifteo::AssetImage CSV;
extern const Sifteo::AssetImage EnzOverview;
extern const Sifteo::AssetImage Reaction;
extern const Sifteo::AssetImage Data;
extern const Sifteo::AssetImage SelectCSV;
